### PR TITLE
Build process automation and Visual Studio 2013 support

### PR DESCRIPTION
**Pull request by mcleary**
I added some code in the **3rdPartyBuild.cmd** and **CMakeLists** in general to support Visual Studio 2013 and Qt 5.4.

The explicit operator bool() is working fine in VS2013.

I remove the need to set the environment variables **DPHOME** and **DP_3RDHOME_PATH**. The root CMakeLists should initialize this variables automatically using **CMAKE_CURRENT_SOURCE_DIR**

The script to build 3rdparty libraries was updated to support VS2013. The **3rdPartyBuild.cmake** has options to choose which dependencies to build. The user should be able to choose an installed version of the boost library for instance, same for other libs.

The **CopyQtDlls** tools expects **QTDIR** set as an environment variable. The Qt home path can be deduced from **Qt5Core_DIR**.

There was a problem linking with freeglut. The link from where freeglut is downloaded provides only release version of the lib. In the **freeglut.h** header there as a **#pragma comment(lib, "freeglutd.lib")**. Since this file doesn't exists in the packege the build fails. This was solved using the **/NODEFAULTLIB** option of Visual Studio linker. All cmake targets that need to link with freeglut were updated.

### CODE REVIEW

**Comment by mtavenrath** [comment]
Hi,

thank you for implementing those changes. Before I can merge the pull request I have to do some administrative tasks. I'll come back to you next week.

Best Regards,

Markus

**Comment by mcleary** [comment]
Hi @mtavenrath, since this is my first pull request ever I was wondering what is the recommendation for new pull requests. I notice that any commit to my local master branch automatically updates this pull request. 

Do you have a suggestion on how to proceed in case of new modifications? I was reading that one can create a branch just to make the pull request.

What do you recommend?

**Comment by mtavenrath** [comment]
Hi @mcleary. All modifications should be made in a different branch than the master branch. This way you can always fast forward from the master branch of nvpro-pipeline.

I'd prefer to have a rebased big changelist of all the small changes you made if possible. Rebasing in the master branch shouldn't be done since it'll mess with the history of all people who cloned this branch.

Before rebasing you should create a new local branch to ensure that you don't destroy your local history if something goes wrong.

**Comment by mcleary** [comment]
I'll work to rebase my modifications. You can reject this pull request since I'll try to create a new one with a single big change.

Thanks for the advice.

**Comment by mtavenrath** [comment]
Closing as there's a new pull request

**Pull request closed without merging**
